JetEnergy Corrections:
    name: JERC
    path: Wprime.Modules.JetCorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod
        runEra: self.dataset.runEra

Type-I MET correction:
    name: TypeICorrectedMET
    path: Wprime.Modules.METcorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod
        runEra: self.dataset.runEra

MET filters:
    name: METfilter
    path: Wprime.Modules.METfilters
    parameters:
        year: self.config.year

To compute effective MET for Oscar:
    name: METprime
    path: Wprime.Modules.plotUtils

deltaPhi(muon, MET):
    name: deltaPhi
    path: Wprime.Modules.plotUtils

Jet cleanup:
    name: jetCleanup
    path: Wprime.Modules.plotUtils

#To compute gen-level Wmass & Wpt:
#    name: genVars
#    path: Wprime.Modules.plotUtils
#    parameters:
#        isMC: self.dataset.process.isMC
#        isPythia: self.dataset.process.get_aux('isPythia', False)

#PUweight from ROOT files:
#    name: puWeightRDF
#    path: Corrections.LUM.puWeight
#    parameters:
#        isMC: self.dataset.process.isMC
#        year: self.config.year
#        isUL: self.dataset.has_tag('ul')
#        postEE: self.dataset.has_tag('postEE')

PUweight from correctionlib:
    name: puWeightRun3
    path: Wprime.Modules.puWeightCor
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod

Muon SFs:
    name: MuonSF
    path: Wprime.Modules.muonSF
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod

#Apply k-factor for HT-binned:
#    name: HTkfactor
#    path: Wprime.Modules.kfactor_Wboost
#    parameters:
#        isHTbin: self.dataset.process.get_aux('isHTbin', False)