Golden_JSON:
    name: lumiFilterRDF
    path: Wprime.Modules.lumiFilter
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

HLT Trigger path:
    name: ElectronPath
    path: Wprime.Modules.HLTtrigger
    parameters:
        year: self.config.year

ECAL tower filter:
    name: ECALTowerFilter
    path: Wprime.Modules.METfilters
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

Preselection -> Single Electron Selection:
    name: SingleElectronSelection
    path: Wprime.Modules.SingleEle_Selec

JetEnergy Corrections:
    name: JERCelectron
    path: Wprime.Modules.JetCorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod
        runEra: self.dataset.runEra

Type-I MET correction:
    name: TypeICorrectedMETelectron
    path: Wprime.Modules.METcorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod
        runEra: self.dataset.runEra

MET filters:
    name: METfilter
    path: Wprime.Modules.METfilters
    parameters:
        year: self.config.year

Jet veto maps:
    name: JetVetoMapsElectron
    path: Wprime.Modules.jetvetomap
    parameters:
        year: self.config.year
        runPeriod: self.dataset.runPeriod

Jet cleanup:
    name: jetCleanupElectron
    path: Wprime.Modules.plotUtils

APPLY KINEMATIC SELECTION:
    name: kinSelElectron
    path: Wprime.Modules.kinematicSelection
    parameters:
        year: self.config.year
        runPeriod: self.dataset.runPeriod