MET filters:
    name: METfilter
    path: Wprime.Modules.METfilters
    parameters:
        year: self.config.year

deltaPhi(muon, MET):
    name: deltaPhi
    path: Wprime.Modules.plotUtils
    parameters:
        postEE: self.dataset.has_tag('postEE')
        isMC: self.dataset.process.isMC

Jet cleanup:
    name: jetCleanup
    path: Wprime.Modules.plotUtils