deltaPhi(muon, MET):
    name: deltaPhi
    path: Wprime.Modules.plotUtils
    parameters:
        postEE: self.dataset.has_tag('postEE')
        isMC: self.dataset.process.isMC

To compute effective MET for Oscar:
    name: METprime
    path: Wprime.Modules.plotUtils

MET filters:
    name: METfilter
    path: Wprime.Modules.METfilters
    parameters:
        year: self.config.year

Jet cleanup:
    name: jetCleanup
    path: Wprime.Modules.plotUtils

APPLY KINEMATIC SELECTION:
    name: kinSel
    path: Wprime.Modules.kinematicSelection
    parameters:
        postEE: self.dataset.has_tag('postEE')

#PUweight from ROOT files:
#    name: puWeightRDF
#    path: Corrections.LUM.puWeight
#    parameters:
#        isMC: self.dataset.process.isMC
#        year: self.config.year
#        isUL: self.dataset.has_tag('ul')
#        postEE: self.dataset.has_tag('postEE')

PUweight from correctionlib:
    name: puWeightRun3
    path: Corrections.LUM.puWeightCor
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        postEE: self.dataset.has_tag('postEE')

Muon SFs:
    name: MuonSF
    path: Wprime.Modules.muonSF
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        postEE: self.dataset.has_tag('postEE')

#Apply k-factor for HT-binned:
#    name: HTkfactor
#    path: Wprime.Modules.kfactor_Wboost
#    parameters:
#        isHTbin: self.dataset.process.get_aux('isHTbin', False)