## Modulos para aplicar a los trigger checks de Oscar ##

Golden_JSON:
    name: lumiFilterRDF
    path: Base.Modules.lumiFilter
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

Module with MET Trigger paths:
    name: METpath
    path: Wprime.Modules.HLTtrigger
    parameters:
        year: self.config.year

W on-shell Stitching:
    name: Wonshell_Overlap
    path: Wprime.Modules.Wboson_Stitching
    parameters:
        isWjets: self.dataset.process.get_aux('isWjets', False)

Preselection -> Single Muon Selection:
    name: SingleMuonSelection
    path: Wprime.Modules.SingleMuon_Selec

