# PUweight from ROOT files:
#    name: puWeightRDF
#    path: Corrections.LUM.puWeight
#    parameters:
#        isMC: self.dataset.process.isMC
#        year: self.config.year
#        isUL: self.dataset.has_tag('ul')
#        postEE: self.dataset.has_tag('postEE')

PUweight from correctionlib:
    name: puWeightRun3
    path: Corrections.LUM.puWeightCor
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        postEE: self.dataset.has_tag('postEE')

#dystitching:
#    name: DYstitchingRDF
#    path: Tools.Tools.dyreweighting
#    parameters:
#        year: self.config.year
#        isDY: self.dataset.process.get_aux('isDY', False)
#        isUL: self.dataset.has_tag('ul')