# PUweight from ROOT files:
#    name: puWeightRDF
#    path: Corrections.LUM.puWeight
#    parameters:
#        isMC: self.dataset.process.isMC
#        year: self.config.year
#        isUL: self.dataset.has_tag('ul')
#        postEE: self.dataset.has_tag('postEE')

PUweight from correctionlib:
    name: puWeightRun3
    path: Wprime.Modules.puWeightCor
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod
